using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Text;
using Tabkit.Core.Audit;

namespace Tabkit.Core.Output;

/// <summary>
/// Single-file HTML report. No JS framework, no runtime. The CSS mirrors the
/// dark-theme report shipped by the Python POC.
/// </summary>
public static class HtmlOutput
{
    public static string FindingsToHtml(
        IEnumerable<Finding> findings,
        IEnumerable<IRule>? rules = null,
        string title = "tabkit audit report")
    {
        _ = rules; // currently unused — rule metadata appears via findings
        var list = findings.ToList();
        var byWorkbook = list.GroupBy(f => f.WorkbookPath).ToList();
        var counts = new
        {
            error = list.Count(f => f.Severity == Severity.Error),
            warn = list.Count(f => f.Severity == Severity.Warn),
            info = list.Count(f => f.Severity == Severity.Info),
            total = list.Count,
        };
        var now = DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm:ss 'UTC'", CultureInfo.InvariantCulture);

        var sb = new StringBuilder();
        sb.Append(CSS_HEADER.Replace("{{TITLE}}", WebUtility.HtmlEncode(title)));

        sb.Append($@"
  <header>
    <div class=""brand"">
      <div class=""brand-mark"">tk</div>
      <div class=""brand-text"">
        <h1>{WebUtility.HtmlEncode(title)}</h1>
        <small>tabkit · static analysis for Tableau workbooks</small>
      </div>
    </div>
    <div class=""meta"">
      <div>tabkit v{ThisAssembly.Version}</div>
      <div>{now}</div>
    </div>
  </header>

  <section class=""stats"">
    <div class=""stat""><div class=""label"">Findings</div><div class=""value"">{counts.total}</div></div>
    <div class=""stat error""><div class=""label"">Errors</div><div class=""value"">{counts.error}</div></div>
    <div class=""stat warn""><div class=""label"">Warnings</div><div class=""value"">{counts.warn}</div></div>
    <div class=""stat info""><div class=""label"">Info</div><div class=""value"">{counts.info}</div></div>
  </section>
");

        if (counts.total == 0)
        {
            sb.Append(@"
    <div class=""empty-ok"">
      <div class=""check"">✓</div>
      <h3>All rules passed</h3>
      <p>No findings across the scanned workbook(s).</p>
    </div>");
        }
        else
        {
            foreach (var group in byWorkbook)
            {
                sb.Append($@"
    <section class=""workbook"">
      <h2>Workbook</h2>
      <div class=""path"">{WebUtility.HtmlEncode(group.Key)}</div>
");
                foreach (var f in group)
                {
                    var sev = f.Severity.AsString();
                    sb.Append($@"
      <div class=""finding {sev}"">
        <div class=""finding-head"">
          <div>
            <div class=""finding-id"">{WebUtility.HtmlEncode(f.RuleId)}</div>
            <div class=""finding-title"">{WebUtility.HtmlEncode(f.Title)}</div>
          </div>
          <span class=""severity-pill {sev}"">{sev}</span>
        </div>
        <div class=""finding-msg"">{WebUtility.HtmlEncode(f.Message)}</div>
");
                    if (!string.IsNullOrEmpty(f.Location))
                        sb.Append($"        <div class=\"finding-loc\">{WebUtility.HtmlEncode(f.Location)}</div>\n");
                    if (!string.IsNullOrEmpty(f.Remediation))
                        sb.Append($"        <div class=\"finding-rem\">{WebUtility.HtmlEncode(f.Remediation)}</div>\n");
                    sb.Append("      </div>\n");
                }
                sb.Append("    </section>\n");
            }
        }

        sb.Append(@"
  <footer>
    Generated by <strong>tabkit</strong> · single-file static report · no runtime
  </footer>
</main>
</body>
</html>
");
        return sb.ToString();
    }

    private const string CSS_HEADER = @"<!doctype html>
<html lang=""en"">
<head>
<meta charset=""utf-8"">
<title>{{TITLE}}</title>
<meta name=""viewport"" content=""width=device-width, initial-scale=1"">
<style>
  :root {
    --bg: oklch(0.16 0.005 250);
    --bg-card: oklch(0.20 0.006 250);
    --bg-elevated: oklch(0.24 0.007 250);
    --border: oklch(0.30 0.008 250);
    --text: oklch(0.96 0.005 250);
    --muted: oklch(0.65 0.01 250);
    --brand: oklch(0.66 0.16 250);
    --brand-dim: oklch(0.42 0.16 250);
    --error: oklch(0.65 0.20 25);
    --error-bg: oklch(0.30 0.10 25 / 0.25);
    --warn: oklch(0.78 0.16 80);
    --warn-bg: oklch(0.35 0.10 80 / 0.25);
    --info: oklch(0.72 0.10 200);
    --info-bg: oklch(0.32 0.08 200 / 0.25);
    --ok: oklch(0.72 0.16 160);
    --ok-bg: oklch(0.30 0.10 160 / 0.25);
  }
  * { box-sizing: border-box; }
  html, body { margin: 0; padding: 0; background: var(--bg); color: var(--text); }
  body {
    font-family: ui-sans-serif, system-ui, -apple-system, ""Segoe UI"", Roboto, sans-serif;
    -webkit-font-smoothing: antialiased;
    line-height: 1.55;
  }
  main { max-width: 1100px; margin: 0 auto; padding: 48px 32px 96px; }
  header {
    display: flex; align-items: center; justify-content: space-between;
    padding-bottom: 24px; margin-bottom: 32px;
    border-bottom: 1px solid var(--border);
  }
  .brand { display: flex; align-items: center; gap: 14px; }
  .brand-mark {
    width: 40px; height: 40px; border-radius: 10px;
    background: linear-gradient(135deg, var(--brand), var(--brand-dim));
    display: grid; place-items: center; color: white; font-weight: 800;
    box-shadow: 0 6px 20px oklch(0.42 0.16 250 / 0.4); font-size: 18px;
  }
  .brand-text h1 { font-size: 18px; margin: 0; letter-spacing: -0.01em; }
  .brand-text small { color: var(--muted); font-size: 12px; }
  .meta { color: var(--muted); font-size: 13px; text-align: right; }
  .meta div + div { margin-top: 2px; }

  .stats { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin-bottom: 36px; }
  .stat { background: var(--bg-card); border: 1px solid var(--border); border-radius: 12px; padding: 18px; }
  .stat .label { font-size: 11px; text-transform: uppercase; letter-spacing: 0.08em; color: var(--muted); }
  .stat .value { font-size: 32px; font-weight: 700; margin-top: 6px; font-variant-numeric: tabular-nums; }
  .stat.error .value { color: var(--error); }
  .stat.warn  .value { color: var(--warn); }
  .stat.info  .value { color: var(--info); }

  .workbook { margin-bottom: 40px; }
  .workbook h2 {
    font-size: 14px; text-transform: uppercase; letter-spacing: 0.06em;
    color: var(--muted); margin: 0 0 12px; font-weight: 600;
  }
  .workbook .path {
    font-family: ui-monospace, ""JetBrains Mono"", Consolas, monospace;
    font-size: 13px; color: var(--text); background: var(--bg-card);
    border: 1px solid var(--border); padding: 8px 12px; border-radius: 8px;
    word-break: break-all; margin-bottom: 16px;
  }

  .finding {
    background: var(--bg-card); border: 1px solid var(--border);
    border-left: 3px solid var(--border);
    border-radius: 10px; padding: 16px 18px; margin-bottom: 10px;
  }
  .finding.error { border-left-color: var(--error); }
  .finding.warn  { border-left-color: var(--warn); }
  .finding.info  { border-left-color: var(--info); }

  .finding-head { display: flex; align-items: baseline; justify-content: space-between; gap: 16px; }
  .finding-id { font-family: ui-monospace, Consolas, monospace; font-size: 11px; color: var(--muted); letter-spacing: 0.04em; }
  .finding-title { font-weight: 600; font-size: 14px; }
  .severity-pill {
    display: inline-block; padding: 2px 8px; border-radius: 999px;
    font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.06em;
  }
  .severity-pill.error { background: var(--error-bg); color: var(--error); }
  .severity-pill.warn  { background: var(--warn-bg); color: var(--warn); }
  .severity-pill.info  { background: var(--info-bg); color: var(--info); }

  .finding-msg { color: var(--text); font-size: 14px; margin-top: 8px; }
  .finding-loc {
    font-family: ui-monospace, Consolas, monospace; font-size: 12px; color: var(--muted);
    background: var(--bg-elevated); padding: 4px 8px; border-radius: 6px; display: inline-block;
    margin-top: 8px;
  }
  .finding-rem {
    color: var(--muted); font-size: 13px; margin-top: 10px;
    padding-left: 10px; border-left: 2px solid var(--border);
  }
  .empty-ok {
    text-align: center; padding: 64px 32px;
    background: var(--ok-bg); border: 1px solid oklch(0.55 0.16 160 / 0.4);
    border-radius: 16px;
  }
  .empty-ok .check {
    width: 64px; height: 64px; border-radius: 50%; background: oklch(0.55 0.18 160);
    margin: 0 auto 16px; display: grid; place-items: center; font-size: 28px; color: white;
  }
  .empty-ok h3 { margin: 0 0 8px; font-size: 18px; }
  .empty-ok p { color: var(--muted); margin: 0; font-size: 14px; }

  footer { color: var(--muted); font-size: 12px; margin-top: 64px; padding-top: 24px;
           border-top: 1px solid var(--border); text-align: center; }
</style>
</head>
<body>
<main>
";
}
